spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: "This is attempt to try the actuator/prometheus/grafana service"
    version: "1.0.0"
    description: "This user service for nothing!"

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
